# Generated by Django 5.2.4 on 2025-08-31 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("matricula_id", models.CharField(max_length=20, unique=True)),
                ("nome_completo", models.CharField(max_length=100)),
                ("id_nacional", models.CharField(blank=True, max_length=20, null=True)),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("endereco", models.TextField()),
                ("data_matricula", models.DateField()),
                ("data_nascimento", models.DateField()),
                ("data_saida", models.DateField(blank=True, null=True)),
                ("status_ativo", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "pessoa_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pessoas.pessoa",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("pessoas.pessoa",),
        ),
        migrations.CreateModel(
            name="Voluntario",
            fields=[
                (
                    "pessoa_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pessoas.pessoa",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("pessoas.pessoa",),
        ),
    ]
