# Generated by Django 5.2.4 on 2025-08-31 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patrocinador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=150)),
                (
                    "telefone_contato",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "documento_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "campo_atividade",
                    models.CharField(
                        choices=[
                            ("EDUCAO", "Educação e Treinamento"),
                            ("ESPORTE", "Esporte e Recreação"),
                            ("ARTES", "Artes e Cultura"),
                            ("SAUDE", "Saúde e Bem-estar"),
                            ("COMUNIDADE", "Desenvolvimento Comunitário"),
                            ("MEIO_AMBIENTE", "Meio Ambiente"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FinanciamentoEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data", models.DateField(auto_now_add=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financiamentos",
                        to="eventos.evento",
                    ),
                ),
                (
                    "patrocinador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financiamentos",
                        to="patrocinadores.patrocinador",
                    ),
                ),
            ],
            options={
                "unique_together": {("patrocinador", "evento")},
            },
        ),
    ]
